use day3;
show tables;
select * from myemp;

# WHERE clause

#1. Get EMP_ID, FIRST_NAME, LAST_NAME and EMAIL OF EMPLOYEES FROM DEPARTMENT WITH DEP_ID 50

SELECT 
	EMP_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    DEP_ID
FROM myemp
WHERE DEP_ID = 50;

#2. GET SALARIES OF IT PROFESSIONALS FROM THE EMPLOYEE TABLE (JOB_ID = IT_PROG)

SELECT 
	EMP_ID,
    SALARY,
    JOB_ID
FROM myemp
WHERE JOB_ID = 'IT_PROG';

#3. Get EMP_ID & HIRE_DATE OF EMPLOYEES HAVING SALARY LESS THAN 15000 (OPERATOR: <)

SELECT
	EMP_ID,
    HIRE_DATE,
    SALARY
FROM myemp
WHERE SALARY<15000;

#4. Get EMP_ID & HIRE_DATE OF EMPLOYEES HAVING SALARY GREATER THAN 15000 (OPERATOR: >)

SELECT
	EMP_ID,
    HIRE_DATE,
    SALARY
FROM myemp
WHERE SALARY>15000;

#5. Get EMP_ID & HIRE_DATE OF EMPLOYEES HAVING SALARY ATLEAST 15000 (OPERATOR: >=)

SELECT
	EMP_ID,
    HIRE_DATE,
    SALARY
FROM myemp
WHERE SALARY>=15000;

#6. Get EMP_ID & HIRE_DATE OF EMPLOYEES HAVING SALARY ATMOST 15000 (OPERATOR: <=)

SELECT
	EMP_ID,
    HIRE_DATE,
    SALARY
FROM myemp
WHERE SALARY<=15000;


#WHERE clause: BETWEEN Operator

#1. Get EMP_ID HIRE_DATE OF employees having salary from 10000 to 20000

SELECT
	EMP_ID,
    HIRE_DATE,
    SALARY
FROM myemp
WHERE SALARY BETWEEN 10000 AND 20000;
